name: bible_side
description: Bible app
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  stacked: ^3.4.2
  stacked_themes: ^0.3.12
  stacked_services: ^1.5.0
  stacked_hooks: ^0.2.3
  flutter_hooks: ^0.18.6

  material_symbols_icons: ^4.2719.3
  linked_scroll_controller: ^0.2.0
  scrollable_positioned_list: ^0.3.8
  infinite_scroll_pagination: ^4.0.0
  visibility_detector: ^0.4.0+2
  package_info_plus: ^7.0.0
  shared_preferences: ^2.2.3

dev_dependencies:
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  mockito: ^5.4.1
  stacked_generator: ^1.6.0

flutter:

  fonts:
    - family: RobotoSerif
      fonts:
        - asset: assets/fonts/RobotoSerif/RobotoSerif-Regular.ttf
          weight: 400
        - asset: assets/fonts/RobotoSerif/RobotoSerif-Medium.ttf
          weight: 500
        - asset: assets/fonts/RobotoSerif/RobotoSerif-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/RobotoSerif/RobotoSerif-Bold.ttf
          weight: 700

  uses-material-design: true

  assets:
    - assets/images/

    - assets/bibles/KJV/GEN.json

    - assets/bibles/KJV/EXO.json

    - assets/bibles/KJV/LEV.json

    - assets/bibles/KJV/NUM.json

    - assets/bibles/KJV/DEU.json

    - assets/bibles/KJV/JOS.json

    - assets/bibles/KJV/JDG.json

    - assets/bibles/KJV/RUT.json

    - assets/bibles/KJV/SA1.json

    - assets/bibles/KJV/SA2.json

    - assets/bibles/KJV/KI1.json

    - assets/bibles/KJV/KI2.json

    - assets/bibles/KJV/CH1.json

    - assets/bibles/KJV/CH2.json

    - assets/bibles/KJV/EZR.json

    - assets/bibles/KJV/NEH.json

    - assets/bibles/KJV/EST.json

    - assets/bibles/KJV/JOB.json

    - assets/bibles/KJV/PSA.json

    - assets/bibles/KJV/PRO.json

    - assets/bibles/KJV/ECC.json

    - assets/bibles/KJV/SNG.json

    - assets/bibles/KJV/ISA.json

    - assets/bibles/KJV/JER.json

    - assets/bibles/KJV/LAM.json

    - assets/bibles/KJV/EZE.json

    - assets/bibles/KJV/DAN.json

    - assets/bibles/KJV/HOS.json

    - assets/bibles/KJV/JOL.json

    - assets/bibles/KJV/AMO.json

    - assets/bibles/KJV/OBA.json

    - assets/bibles/KJV/JNA.json

    - assets/bibles/KJV/MIC.json

    - assets/bibles/KJV/NAH.json

    - assets/bibles/KJV/HAB.json

    - assets/bibles/KJV/ZEP.json

    - assets/bibles/KJV/HAG.json

    - assets/bibles/KJV/ZEC.json

    - assets/bibles/KJV/MAL.json


    - assets/bibles/OET-RV/MAT.json
    - assets/bibles/OET-LV/MAT.json
    - assets/bibles/KJV/MAT.json

    - assets/bibles/OET-RV/MRK.json
    - assets/bibles/OET-LV/MRK.json
    - assets/bibles/KJV/MRK.json

    - assets/bibles/OET-RV/LUK.json
    - assets/bibles/OET-LV/LUK.json
    - assets/bibles/KJV/LUK.json

    - assets/bibles/OET-RV/JHN.json
    - assets/bibles/OET-LV/JHN.json
    - assets/bibles/KJV/JHN.json

    - assets/bibles/OET-RV/ACT.json
    - assets/bibles/OET-LV/ACT.json
    - assets/bibles/KJV/ACT.json

    - assets/bibles/OET-RV/ROM.json
    - assets/bibles/OET-LV/ROM.json
    - assets/bibles/KJV/ROM.json

    - assets/bibles/OET-RV/CO1.json
    - assets/bibles/OET-LV/CO1.json
    - assets/bibles/KJV/CO1.json

    - assets/bibles/OET-RV/CO2.json
    - assets/bibles/OET-LV/CO2.json
    - assets/bibles/KJV/CO2.json

    - assets/bibles/OET-RV/GAL.json
    - assets/bibles/OET-LV/GAL.json
    - assets/bibles/KJV/GAL.json

    - assets/bibles/OET-RV/EPH.json
    - assets/bibles/OET-LV/EPH.json
    - assets/bibles/KJV/EPH.json

    - assets/bibles/OET-RV/PHP.json
    - assets/bibles/OET-LV/PHP.json
    - assets/bibles/KJV/PHP.json

    - assets/bibles/OET-RV/COL.json
    - assets/bibles/OET-LV/COL.json
    - assets/bibles/KJV/COL.json

    - assets/bibles/OET-RV/TH1.json
    - assets/bibles/OET-LV/TH1.json
    - assets/bibles/KJV/TH1.json

    - assets/bibles/OET-RV/TH2.json
    - assets/bibles/OET-LV/TH2.json
    - assets/bibles/KJV/TH2.json

    - assets/bibles/OET-RV/TI1.json
    - assets/bibles/OET-LV/TI1.json
    - assets/bibles/KJV/TI1.json

    - assets/bibles/OET-RV/TI2.json
    - assets/bibles/OET-LV/TI2.json
    - assets/bibles/KJV/TI2.json

    - assets/bibles/OET-RV/TIT.json
    - assets/bibles/OET-LV/TIT.json
    - assets/bibles/KJV/TIT.json

    - assets/bibles/OET-RV/PHM.json
    - assets/bibles/OET-LV/PHM.json
    - assets/bibles/KJV/PHM.json

    - assets/bibles/OET-RV/HEB.json
    - assets/bibles/OET-LV/HEB.json
    - assets/bibles/KJV/HEB.json

    - assets/bibles/OET-RV/ACT.json
    - assets/bibles/OET-LV/ACT.json
    - assets/bibles/KJV/ACT.json

    - assets/bibles/OET-RV/JAM.json
    - assets/bibles/OET-LV/JAM.json
    - assets/bibles/KJV/JAM.json

    - assets/bibles/OET-RV/PE1.json
    - assets/bibles/OET-LV/PE1.json
    - assets/bibles/KJV/PE1.json

    - assets/bibles/OET-RV/PE2.json
    - assets/bibles/OET-LV/PE2.json
    - assets/bibles/KJV/PE2.json

    - assets/bibles/OET-RV/JN1.json
    - assets/bibles/OET-LV/JN1.json
    - assets/bibles/KJV/JN1.json

    - assets/bibles/OET-RV/JN2.json
    - assets/bibles/OET-LV/JN2.json
    - assets/bibles/KJV/JN2.json

    - assets/bibles/OET-RV/JN3.json
    - assets/bibles/OET-LV/JN3.json
    - assets/bibles/KJV/JN3.json

    - assets/bibles/OET-RV/JDE.json
    - assets/bibles/OET-LV/JDE.json
    - assets/bibles/KJV/JDE.json

    - assets/bibles/OET-RV/REV.json
    - assets/bibles/OET-LV/REV.json
    - assets/bibles/KJV/REV.json
