name: bible_side
description: Bible app
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  stacked: ^3.4.0
  stacked_themes: ^0.3.12
  stacked_services: ^1.1.0
  stacked_hooks: ^0.2.3
  flutter_hooks: ^0.18.6

  material_symbols_icons: ^4.2706.0
  linked_scroll_controller: ^0.2.0
  scrollable_positioned_list: ^0.3.8
  infinite_scroll_pagination: ^4.0.0
  visibility_detector: ^0.4.0+2
  package_info_plus: ^4.2.0
  shared_preferences: ^2.2.2

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/

    - assets/bibles/OET-RV/MAT.json
    - assets/bibles/OET-LV/MAT.json

    - assets/bibles/OET-RV/MRK.json
    - assets/bibles/OET-LV/MRK.json

    - assets/bibles/OET-RV/LUK.json
    - assets/bibles/OET-LV/LUK.json

    - assets/bibles/OET-RV/JHN.json
    - assets/bibles/OET-LV/JHN.json

    - assets/bibles/OET-RV/ACT.json
    - assets/bibles/OET-LV/ACT.json

    - assets/bibles/OET-RV/ROM.json
    - assets/bibles/OET-LV/ROM.json

    - assets/bibles/OET-RV/CO1.json
    - assets/bibles/OET-LV/CO1.json

    - assets/bibles/OET-RV/CO2.json
    - assets/bibles/OET-LV/CO2.json

    - assets/bibles/OET-RV/GAL.json
    - assets/bibles/OET-LV/GAL.json

    - assets/bibles/OET-RV/EPH.json
    - assets/bibles/OET-LV/EPH.json

    - assets/bibles/OET-RV/PHP.json
    - assets/bibles/OET-LV/PHP.json

    - assets/bibles/OET-RV/COL.json
    - assets/bibles/OET-LV/COL.json

    - assets/bibles/OET-RV/TH1.json
    - assets/bibles/OET-LV/TH1.json

    - assets/bibles/OET-RV/TH2.json
    - assets/bibles/OET-LV/TH2.json

    - assets/bibles/OET-RV/TI1.json
    - assets/bibles/OET-LV/TI1.json

    - assets/bibles/OET-RV/TI2.json
    - assets/bibles/OET-LV/TI2.json

    - assets/bibles/OET-RV/TIT.json
    - assets/bibles/OET-LV/TIT.json

    - assets/bibles/OET-RV/PHM.json
    - assets/bibles/OET-LV/PHM.json

    - assets/bibles/OET-RV/HEB.json
    - assets/bibles/OET-LV/HEB.json

    - assets/bibles/OET-RV/ACT.json
    - assets/bibles/OET-LV/ACT.json

    - assets/bibles/OET-RV/JAM.json
    - assets/bibles/OET-LV/JAM.json

    - assets/bibles/OET-RV/PE1.json
    - assets/bibles/OET-LV/PE1.json

    - assets/bibles/OET-RV/PE2.json
    - assets/bibles/OET-LV/PE2.json

    - assets/bibles/OET-RV/JN1.json
    - assets/bibles/OET-LV/JN1.json

    - assets/bibles/OET-RV/JN2.json
    - assets/bibles/OET-LV/JN2.json

    - assets/bibles/OET-RV/JN3.json
    - assets/bibles/OET-LV/JN3.json

    - assets/bibles/OET-RV/JDE.json
    - assets/bibles/OET-LV/JDE.json

    - assets/bibles/OET-RV/REV.json
    - assets/bibles/OET-LV/REV.json
