name: bible_side
description: Bible app
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  material_symbols_icons: ^4.2706.0
  linked_scroll_controller: ^0.2.0
  visibility_detector: ^0.4.0+2
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  package_info_plus: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true


  assets:
    - assets/OET/RV/MAT.json
    - assets/OET/LV/MAT.json

    - assets/OET/RV/MRK.json
    - assets/OET/LV/MRK.json

    - assets/OET/RV/LUK.json
    - assets/OET/LV/LUK.json

    - assets/OET/RV/JHN.json
    - assets/OET/LV/JHN.json

    - assets/OET/RV/ACT.json
    - assets/OET/LV/ACT.json

    - assets/OET/RV/ROM.json
    - assets/OET/LV/ROM.json

    - assets/OET/RV/CO1.json
    - assets/OET/LV/CO1.json

    - assets/OET/RV/CO2.json
    - assets/OET/LV/CO2.json

    - assets/OET/RV/GAL.json
    - assets/OET/LV/GAL.json

    - assets/OET/RV/EPH.json
    - assets/OET/LV/EPH.json

    - assets/OET/RV/PHP.json
    - assets/OET/LV/PHP.json

    - assets/OET/RV/COL.json
    - assets/OET/LV/COL.json

    - assets/OET/RV/TH1.json
    - assets/OET/LV/TH1.json

    - assets/OET/RV/TH2.json
    - assets/OET/LV/TH2.json

    - assets/OET/RV/TI1.json
    - assets/OET/LV/TI1.json

    - assets/OET/RV/TI2.json
    - assets/OET/LV/TI2.json

    - assets/OET/RV/TIT.json
    - assets/OET/LV/TIT.json

    - assets/OET/RV/PHM.json
    - assets/OET/LV/PHM.json

    - assets/OET/RV/HEB.json
    - assets/OET/LV/HEB.json

    - assets/OET/RV/ACT.json
    - assets/OET/LV/ACT.json

    - assets/OET/RV/JAM.json
    - assets/OET/LV/JAM.json

    - assets/OET/RV/PE1.json
    - assets/OET/LV/PE1.json

    - assets/OET/RV/PE2.json
    - assets/OET/LV/PE2.json

    - assets/OET/RV/JN1.json
    - assets/OET/LV/JN1.json

    - assets/OET/RV/JN2.json
    - assets/OET/LV/JN2.json

    - assets/OET/RV/JN3.json
    - assets/OET/LV/JN3.json

    - assets/OET/RV/JDE.json
    - assets/OET/LV/JDE.json

    - assets/OET/RV/REV.json
    - assets/OET/LV/REV.json
