name: bible_side
description: Bible app
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  material_symbols_icons: ^4.2706.0
  linked_scroll_controller: ^0.2.0
  visibility_detector: ^0.4.0+2
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  package_info_plus: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true


  assets:
    - assets/OET/RV/ACT.json
    - assets/OET/LV/ACT.json

    - assets/OET/RV/JHN.json
    - assets/OET/LV/JHN.json

    - assets/OET/RV/MAT.json
    - assets/OET/LV/MAT.json

    - assets/OET/RV/MRK.json
    - assets/OET/LV/MRK.json

    - assets/OET/RV/LUK.json
    - assets/OET/LV/LUK.json